/Applications/MaciASL.app/Contents/MacOS/iasl-stable ./APIC.aml
/Applications/MaciASL.app/Contents/MacOS/iasl-stable ./BGRT.aml
/Applications/MaciASL.app/Contents/MacOS/iasl-stable ./BOOT.aml
/Applications/MaciASL.app/Contents/MacOS/iasl-stable ./DBG2.aml
/Applications/MaciASL.app/Contents/MacOS/iasl-stable ./DBGP.aml
/Applications/MaciASL.app/Contents/MacOS/iasl-stable ./DSDT.aml
/Applications/MaciASL.app/Contents/MacOS/iasl-stable ./DumpLog.txt
/Applications/MaciASL.app/Contents/MacOS/iasl-stable ./FACP.aml
/Applications/MaciASL.app/Contents/MacOS/iasl-stable ./FACS.aml
/Applications/MaciASL.app/Contents/MacOS/iasl-stable ./FIDT.aml
/Applications/MaciASL.app/Contents/MacOS/iasl-stable ./FPDT.aml
/Applications/MaciASL.app/Contents/MacOS/iasl-stable ./HPET.aml
/Applications/MaciASL.app/Contents/MacOS/iasl-stable ./LPIT.aml
/Applications/MaciASL.app/Contents/MacOS/iasl-stable ./MCFG.aml
/Applications/MaciASL.app/Contents/MacOS/iasl-stable ./MSDM.aml
/Applications/MaciASL.app/Contents/MacOS/iasl-stable ./NHLT.aml
/Applications/MaciASL.app/Contents/MacOS/iasl-stable ./RSDP.aml
/Applications/MaciASL.app/Contents/MacOS/iasl-stable ./RSDT.aml
/Applications/MaciASL.app/Contents/MacOS/iasl-stable ./SLIC.aml
/Applications/MaciASL.app/Contents/MacOS/iasl-stable ./SSDT-0-CpuSsdt.aml
/Applications/MaciASL.app/Contents/MacOS/iasl-stable ./SSDT-1-DptfTabl.aml
/Applications/MaciASL.app/Contents/MacOS/iasl-stable ./SSDT-10-UsbCTabl.aml
/Applications/MaciASL.app/Contents/MacOS/iasl-stable ./SSDT-11-CompCMFC.aml
/Applications/MaciASL.app/Contents/MacOS/iasl-stable ./SSDT-12-DscAtiBD.aml
/Applications/MaciASL.app/Contents/MacOS/iasl-stable ./SSDT-13-NveTabl.aml
/Applications/MaciASL.app/Contents/MacOS/iasl-stable ./SSDT-2-CompTabl.aml
/Applications/MaciASL.app/Contents/MacOS/iasl-stable ./SSDT-3-SaSsdt.aml
/Applications/MaciASL.app/Contents/MacOS/iasl-stable ./SSDT-4-PegSsdt.aml
/Applications/MaciASL.app/Contents/MacOS/iasl-stable ./SSDT-5-CmlS_Tbt.aml
/Applications/MaciASL.app/Contents/MacOS/iasl-stable ./SSDT-6-xh_cmsd4.aml
/Applications/MaciASL.app/Contents/MacOS/iasl-stable ./SSDT-7-PerfTune.aml
/Applications/MaciASL.app/Contents/MacOS/iasl-stable ./SSDT-8-PtidDevc.aml
/Applications/MaciASL.app/Contents/MacOS/iasl-stable ./SSDT-9-TbtTypeC.aml
/Applications/MaciASL.app/Contents/MacOS/iasl-stable ./SSDT-x0_0-Cpu0Ist.aml
/Applications/MaciASL.app/Contents/MacOS/iasl-stable ./SSDT-x0_1-ApIst.aml
/Applications/MaciASL.app/Contents/MacOS/iasl-stable ./SSDT-x0_2-Cpu0Cst.aml
/Applications/MaciASL.app/Contents/MacOS/iasl-stable ./SSDT-x0_3-ApCst.aml
/Applications/MaciASL.app/Contents/MacOS/iasl-stable ./SSDT-x0_4-Cpu0Hwp.aml
/Applications/MaciASL.app/Contents/MacOS/iasl-stable ./SSDT-x0_5-ApHwp.aml
/Applications/MaciASL.app/Contents/MacOS/iasl-stable ./SSDT-x0_6-HwpLvt.aml
/Applications/MaciASL.app/Contents/MacOS/iasl-stable ./SSDT-x0_7-Cpu0Psd.aml
/Applications/MaciASL.app/Contents/MacOS/iasl-stable ./SSDT-x0_8-ApPsd.aml
/Applications/MaciASL.app/Contents/MacOS/iasl-stable ./TPM2.aml
/Applications/MaciASL.app/Contents/MacOS/iasl-stable ./VFCT.aml
/Applications/MaciASL.app/Contents/MacOS/iasl-stable ./WSMT.aml
/Applications/MaciASL.app/Contents/MacOS/iasl-stable ./XSDT.aml
/Applications/MaciASL.app/Contents/MacOS/iasl-stable ./a.sh
/Applications/MaciASL.app/Contents/MacOS/iasl-stable ./iasl
